# These are changeable configurations, that each have high/low mappings
# I have ordered this to align the logic of the code with Dr. Kremer's graph
configuration_mappings:
  - Insertion_bias:
      High: TE_Insertion_Distribution = Triangle( pmax=0, pzero=3.0/3.0 );
            Gene_Insertion_Distribution = Triangle( pzero=1.0/3.0, pmax=1 );
      Low: TE_Insertion_Distribution = Flat();
           Gene_Insertion_Distribution = Flat();
  - TE_death_rate:
      High: 0.005
      Low: 0.0005
  - TE_excision_rate:
      High: 0.5
      Low: 0.1
  - TE_progeny:
      High: ProbabilityTable( 0.00, 0, 0.55, 1, 0.30, 2, 0.15, 3 )
      Low: ProbabilityTable( 0.15, 0, 0.55, 1, 0.30, 2 )
  - Carrying_Capacity:
      High: 300
      Low: 30
  - Mutation_effect:
      High: 0.1
      Low: 0.01
  - NC_BP:
      High: 14000000
      Low: 1400000
  - Corrected_mutation_rate:
      High: 0.3
      Low: 0.03

# TODO: These will be added once the original configurations are written
# Autonomous_Frequency:
#   High: 0.8
#   Low: 0.4
# Kidnapping_Frequency:
#   High: Kidnapping_Frequency = lambda live_aut: 1 - 1/(1 + 0.001 * live_aut)
#   Low: Kidnapping_Frequency = lambda live_aut: 1 - 1/(1 + 0.01 * live_aut)